services:
  cosy-cpu:
    container_name: 'cosy-train'
    build: .
    image: cosy-voice:latest # please change the image name and tag base your environment. If the tag contains the word 'elite', such as "latest-elite", it indicates that the image does not include the necessary models such as GPT-SoVITS, UVR5, Damo ASR, etc. You will need to download them yourself and map them into the container.
    environment:
      - is_half=False
      - is_share=False
      - TZ=Asia/Shanghai
      - LC_ALL=en_US.UTF-8
      - PYTHONIOENCODING=UTF-8
      - PYTHONPATH=./:./third_party/Matcha-TTS:./third_party/AcademiCodec
    volumes:
      - type: volume
        source: TTD
        target: /opt/CosyVoice/data/ttd_lib
        volume:
          nocopy: true
          subpath: 00_项目
      - type: volume
        source: TTD-Data
        target: /opt/CosyVoice/data
        volume:
          nocopy: true
          subpath: cosy-voice
      - type: volume
        source: TTD-Data
        target: /opt/CosyVoice/.cache
        volume:
          nocopy: true
          subpath: cosy-voice/.cache
      - type: volume
        source: TTD-Data
        target: /opt/CosyVoice/data/outputs
        volume:
          nocopy: true
          subpath: cosy-voice/output
      - type: volume
        source: TTD-Data
        target: /opt/CosyVoice/data/vc_weights
        volume:
          nocopy: true
          subpath: rvc-web/weights
    working_dir: /opt/CosyVoice
    shm_size: 32G
    stdin_open: true
    tty: true
    restart: unless-stopped
    extra_hosts:
      - "ttd-stage:host-gateway"
    ports:
      #For CPU
      - "9857:9883" #train

  cosy-3070:
    container_name: 'cosy-3070'
    extends: cosy-cpu
    command: [ "python", "webui_auto.py", "2>&1", "|", "stdbuf", "-oL", "-eL", "tee", "-i", "logs/auto.log" ]
    ports:
      #  - "9886:8000"
      #  - "9887:9883"
      !override
      - "8001:9884"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "0" ]
              capabilities: [ gpu ]

  cosy-p5000:
    container_name: 'cosy-p5000'
    extends: cosy-cpu
    command: [ "python", "webui_auto.py", "2>&1", "|", "stdbuf", "-oL", "-eL", "tee", "-i", "logs/auto.log" ]
    ports:
      #  - "9866:8000"
      #  - "9867:9883"
      !override
      - "8003:9884"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ "1" ]
              capabilities: [ gpu ]

volumes:
  TTD:
    external: true
  TTD-Data:
    external: true
