services:
  cosy-base:
    build: .
    image: cosy-voice:latest   # please change the image name and tag base your environment. If the tag contains the word 'elite', such as "latest-elite", it indicates that the image does not include the necessary models such as GPT-SoVITS, UVR5, Damo ASR, etc. You will need to download them yourself and map them into the container.
    environment:
      - is_half=False
      - is_share=False
      - LC_ALL=en_US.UTF-8
      - PYTHONIOENCODING=UTF-8       
      - PYTHONPATH=./:./third_party/Matcha-TTS:./third_party/AcademiCodec
    volumes:
      - /home/docker/mnt/TTD-Data/cosy-voice/.cache:/opt/CosyVoice/.cache
      - /home/docker/mnt/TeamSpace/TTD-Space/CosyVoice_Voices:/opt/CosyVoice/voices
      - /home/docker/mnt/TeamSpace/TTD-Space/CosyVoice_Train:/opt/CosyVoice/data
      - /home/docker/mnt/TTD-Data/cosy-voice/pretrained_models:/opt/CosyVoice/pretrained_models
    working_dir: /opt/CosyVoice
    shm_size: 32G
    stdin_open: true
    tty: true
    restart: unless-stopped
#=9886">3070Ti
#=9876">3080Ti
#=9866">P5000
#=9856">测试服（只用CPU）
  cosy-3070:
    container_name: 'cosy-3070'
    profiles:
      - production
    extends: cosy-base
    ports:
      - "9886:8001"
      - "9887:9883"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["2"]
            capabilities: [gpu]
  cosy-3080:
    container_name: 'cosy-3080'
    profiles:
      - production
    extends: cosy-base
    ports:
      - "9876:8001"
      - "9877:9883"

    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["1"]
            capabilities: [gpu]
  cosy-p5000:
    container_name: 'cosy-p5000'  
    profiles:
      - production
    extends: cosy-base
    ports:
      - "9866:8001"
      - "9867:9883" #train
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [gpu]
  cosy-cpu:
    container_name: 'cosy-cpu'
    profiles:
      - production
    extends: cosy-base
    ports:
      - "9856:8001"