services:
  cosy-cpu:
    container_name: 'cosy-train'  
    build: .
    image: cosy-voice:latest   # please change the image name and tag base your environment. If the tag contains the word 'elite', such as "latest-elite", it indicates that the image does not include the necessary models such as GPT-SoVITS, UVR5, Damo ASR, etc. You will need to download them yourself and map them into the container.
    environment:
      - is_half=False
      - is_share=False
      - TZ=Asia/Shanghai
      - LC_ALL=en_US.UTF-8
      - PYTHONIOENCODING=UTF-8       
      - PYTHONPATH=./:./third_party/Matcha-TTS:./third_party/AcademiCodec
    volumes:
      - /data/ttd/cosy-voice/:/opt/CosyVoice/data  # data_root
      - /mnt/192.168.100.7/00_项目:/opt/CosyVoice/data/ttd_lib  #train voice lib
      - /data/ttd/cosy-voice/.cache:/opt/CosyVoice/.cache # hs/ms cache dir
      - /home/docker/mnt/TeamSpace/TTD-Space/applications/CosyVoice/output:/opt/CosyVoice/data/outputs   #output general
      - /home/docker/mnt/TTD-Data/cosy-voice/hub:/tmp/cosy-voice/hub          #output for ttd.hub
      - /home/docker/mnt/TeamSpace/TTD-Space/applications/rvc-web/assets/weights:/opt/CosyVoice/data/vc_weights  #to be move later
    working_dir: /opt/CosyVoice
    shm_size: 32G
    stdin_open: true
    tty: true
    restart: unless-stopped
    extra_hosts:
    - "ttd-server:host-gateway"
    ports: #For CPU
    #- "9856:8000" #factory_ui
    - "9857:9883" #train
    #- "8004:9884" #auto

  cosy-3070:
    container_name: '3070'
    profiles:
      - production
    extends: cosy-cpu
    command: ["python", "webui_auto.py", "2>&1", "|", "stdbuf", "-oL", "-eL", "tee", "-i", "logs/auto.log"]
    ports: !override
    #  - "9886:8000"
    #  - "9887:9883"
      - "8001:9884"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["2"]
            capabilities: [gpu]
  cosy-3080:
    container_name: '3080'
    profiles:
      - production
    extends: cosy-cpu
    command: ["python", "webui_auto.py", "2>&1", "|", "stdbuf", "-oL", "-eL", "tee", "-i", "logs/auto.log"]
    ports: !override
    #  - "9876:8000"
    #  - "9877:9883"
      - "8002:9884"

    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["1"]
            capabilities: [gpu]
  cosy-p5000:
    container_name: 'p5000'  
    profiles:
      - production
    extends: cosy-cpu
    command: ["python", "webui_auto.py", "2>&1", "|", "stdbuf", "-oL", "-eL", "tee", "-i", "logs/auto.log"]
    ports: !override
    #  - "9866:8000"
    #  - "9867:9883"
      - "8003:9884"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ["0"]
            capabilities: [gpu]
